/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Manager;

import HoaDon.BanHang;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.*;
import ThucDon.*;
import NguoiDung.*;
import KhachHang.*;
import NhanVien.*;

/**
 *
 * @author Shark
 */
public class Main extends javax.swing.JFrame {

     int timeRun=0;
    public Main() {
        initComponents();
        this.lbMNV.setText(frmLogin.manv);
        KeyListener();   
        new Thread()
        {
                public void run()
            {
                while(timeRun==0)
                {
                    Calendar ca=new GregorianCalendar();
                    int second=ca.get(Calendar.SECOND);
                    int minute=ca.get(Calendar.MINUTE);
                    int hour=ca.get(Calendar.HOUR);
                    int AM_PM=ca.get(Calendar.AM_PM);
                    int day=ca.get(Calendar.DAY_OF_MONTH);
                    int month=ca.get(Calendar.MONTH);
                    int year=ca.get(Calendar.YEAR);
                    String day_night="";
                    if(AM_PM==1)
                    {
                        day_night= "PM";
                    }
                    else
                    {
                        day_night= "AM";
                    }
                    String time="Giờ "+hour +":"+minute+":"+second+" "+day_night;
                    txtTime.setText(time);
                    String date="Ngày   "+day+"/"+(month+1)+"/"+year;
                    txtdate.setText(date);
                    
                    
                }
            }
        }.start();
    }
  public void KeyListener()
    {
        this.setFocusable(true);
        this.addKeyListener(new KeyListener(){
            @Override
            public void keyTyped (KeyEvent e)
            {}
            @Override
            public void keyPressed (KeyEvent e)
            {
                if(e.getKeyCode()==KeyEvent.VK_ESCAPE)
                {
                    if(JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn thoát chương trình hay không ?","Thông Báo",2)==0)
                    dispose();
                }     
            }
             @Override
            public void keyReleased (KeyEvent e)
            {}
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        Desktop = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();
        txtdate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbMNV = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mnMent = new javax.swing.JMenuItem();
        mnDislog = new javax.swing.JMenuItem();
        mnExit = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnThucdon = new javax.swing.JMenuItem();
        mbKhachHang = new javax.swing.JMenuItem();
        MNNV = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnAbout = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restairant Sharks");

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1331, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));

        jLabel4.setBackground(new java.awt.Color(255, 204, 51));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Địa Chỉ:");

        jLabel5.setBackground(new java.awt.Color(255, 204, 51));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("181/5 An Phú Đông- Quận 12-HCM");

        txtTime.setBackground(new java.awt.Color(255, 204, 51));
        txtTime.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtTime.setText("Time");

        txtdate.setBackground(new java.awt.Color(255, 204, 51));
        txtdate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtdate.setText("Date");

        jLabel2.setBackground(new java.awt.Color(255, 204, 51));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Người Quản Lý:");

        lbMNV.setBackground(new java.awt.Color(255, 204, 51));
        lbMNV.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbMNV.setText("Tên");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(lbMNV, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lbMNV))
                    .addGap(6, 6, 6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 255, 0)));
        jMenuBar1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jMenu2.setText("Chức Năng");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        mnMent.setText("Quản Lý Người Dùng");
        mnMent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMentActionPerformed(evt);
            }
        });
        jMenu2.add(mnMent);

        mnDislog.setText("Đăng Xuất");
        mnDislog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDislogActionPerformed(evt);
            }
        });
        jMenu2.add(mnDislog);

        mnExit.setText("Thoát");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        jMenu2.add(mnExit);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Danh Mục");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        mnThucdon.setText("Thực Đơn");
        mnThucdon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnThucdonActionPerformed(evt);
            }
        });
        jMenu1.add(mnThucdon);

        mbKhachHang.setText("Khách Hàng");
        mbKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbKhachHangActionPerformed(evt);
            }
        });
        jMenu1.add(mbKhachHang);

        MNNV.setText("Nhân Viên");
        MNNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MNNVActionPerformed(evt);
            }
        });
        jMenu1.add(MNNV);

        jMenuItem3.setText("Bán Hàng");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Trợ Giúp");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        mnAbout.setText("Thông Tin");
        mnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAboutActionPerformed(evt);
            }
        });
        jMenu3.add(mnAbout);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Desktop))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        dispose();
        JOptionPane.showMessageDialog(this, "Tạm Biệt Hẹn Gặp Lại");
    }//GEN-LAST:event_mnExitActionPerformed

    private void mnDislogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDislogActionPerformed
        new frmLogin().show();
        dispose();
    }//GEN-LAST:event_mnDislogActionPerformed

    private void mnThucdonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnThucdonActionPerformed
        DSThucDon TD = new DSThucDon();
        this.Desktop.add(TD).show();
    }//GEN-LAST:event_mnThucdonActionPerformed

    private void mnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAboutActionPerformed
       new About().setVisible(true);
    }//GEN-LAST:event_mnAboutActionPerformed

    private void mnMentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMentActionPerformed
       HeThong HT = new HeThong();
       this.Desktop.add(HT).show();
       
    }//GEN-LAST:event_mnMentActionPerformed

    private void mbKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbKhachHangActionPerformed
       DSKhachHang KH = new DSKhachHang();
       this.Desktop.add(KH).show();
       
    }//GEN-LAST:event_mbKhachHangActionPerformed

    private void MNNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MNNVActionPerformed
      DSNhanVien NV = new  DSNhanVien();
       this.Desktop.add(NV).show();
     
    }//GEN-LAST:event_MNNVActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        BanHang bh = new BanHang();
       this.Desktop.add(bh).show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem MNNV;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbMNV;
    private javax.swing.JMenuItem mbKhachHang;
    private javax.swing.JMenuItem mnAbout;
    private javax.swing.JMenuItem mnDislog;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenuItem mnMent;
    private javax.swing.JMenuItem mnThucdon;
    private javax.swing.JLabel txtTime;
    private javax.swing.JLabel txtdate;
    // End of variables declaration//GEN-END:variables
}
