/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ThucDon;
import java.sql.*;
import javax.swing.*;
import Process.*;
public class DanhMucTD extends javax.swing.JFrame {

    public static String sql="select distinct MaDMTD as 'Mã DM',TenDMTD as 'Tên DM',Ghichu as 'Ghi Chú' from DanhMucTD order by MaDMTD asc";
    public static String madm;
    public DanhMucTD() {
        initComponents();
        showCT();
        ProcessCtr(false);
    }
    public void showCT()
    {
        UpdataTable.LoadData(sql, tbDanhmuc);
        this.lbTong.setText("Tổng Số có"+this.tbDanhmuc.getRowCount()+" Danh Mục");
        
    }
    
public void ProcessCtr(boolean b)
{
    this.btAdd.setEnabled(b);
    this.btEdit.setEnabled(b);
    this.btDel.setEnabled(b);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenDM = new javax.swing.JTextField();
        txtText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaDM = new javax.swing.JTextField();
        btAdd = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btDel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDanhmuc = new javax.swing.JTable();
        New = new javax.swing.JButton();
        lbTong = new javax.swing.JLabel();
        Home = new javax.swing.JButton();
        btRew = new javax.swing.JButton();

        setTitle("Danh Mục Thực Đơn");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Nhập Tên :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Ghi Chú:");

        txtTenDM.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtText.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Danh Mục Thực Đơn");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Mã Danh Mục:");

        txtMaDM.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        btAdd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btAdd.setText("Thêm");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btEdit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btEdit.setText("Sửa");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btDel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btDel.setText("Xoá");
        btDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelActionPerformed(evt);
            }
        });

        tbDanhmuc.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tbDanhmuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbDanhmuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDanhmucMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDanhmuc);

        New.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        New.setText("Nhập Mới");
        New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewActionPerformed(evt);
            }
        });

        lbTong.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lbTong.setText("Danh Muc");

        Home.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Home.setText("Làm Mới");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        btRew.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btRew.setText("Thoát");
        btRew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(lbTong, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtText, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtMaDM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTenDM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Home)
                                            .addComponent(New))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 4, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btAdd)
                                .addGap(30, 30, 30)
                                .addComponent(btEdit)
                                .addGap(27, 27, 27)
                                .addComponent(btDel)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btRew)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRew))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtMaDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(New, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtText, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbTong, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btDel)
                            .addComponent(btEdit)
                            .addComponent(btAdd)
                            .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewActionPerformed
         ProcessCtr(false);
        this.btAdd.setEnabled(true);
        this.txtMaDM.setText(null);
        this.txtTenDM.setText(null);
        this.txtText.setText(null);
    }//GEN-LAST:event_NewActionPerformed

    private void tbDanhmucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDanhmucMouseClicked
        ProcessCtr(true);
        this.btAdd.setEnabled(false);

        try {
            int row = this.tbDanhmuc.getSelectedRow();
            String IDrow =(this.tbDanhmuc.getModel().getValueAt(row, 0)).toString();
            String sql1="select distinct * from DanhMucTD where MaDMTD='"+IDrow+"'";
            ResultSet rs = UpdataTable.ShowTextField(sql1);
            if(rs.next())
            {
                madm =rs.getString("MaDMTD");

                this.txtMaDM.setText(rs.getString("MaDMTD"));
                this.txtTenDM.setText(rs.getString("TenDMTD"));
                this.txtText.setText(rs.getString("Ghichu"));
                

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tbDanhmucMouseClicked

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
       if(this.txtMaDM.getText().length()==0)

        JOptionPane.showMessageDialog(null, "Mã Danh Mục không được bỏ trống", "Thông Báo",1);

        else
        if(this.txtMaDM.getText().length()>10)
        JOptionPane.showMessageDialog(null, "Mã Danh Mục không được quá 10 ký tự ","Thông Báo",1);
        else

        if(this.txtTenDM.getText().length()==0)
        JOptionPane.showMessageDialog(null,"Tên Danh Mục không được bỏ trống","Thông Báo",1);
        
        else
        {

            DanhMuc.InsertDM(this.txtMaDM.getText().trim(), this.txtTenDM.getText(),this.txtText.getText());
            showCT();
            ProcessCtr(false);
        }
    }//GEN-LAST:event_btAddActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        if(this.txtMaDM.getText().length()==0)

        JOptionPane.showMessageDialog(null, "Mã Danh Mục không được bỏ trống", "Thông Báo",1);

        else
        if(this.txtMaDM.getText().length()>10)
        JOptionPane.showMessageDialog(null, "Mã Danh Mục không được quá 10 ký tự ","Thông Báo",1);
        else

        if(this.txtTenDM.getText().length()==0)
        JOptionPane.showMessageDialog(null,"Tên Danh Mục không được bỏ trống","Thông Báo",1);
        else
        {

            DanhMuc.UpdateDM(madm, this.txtMaDM.getText().trim(),this.txtTenDM.getText(),this.txtText.getText());
            showCT();
            ProcessCtr(false);
        }
    }//GEN-LAST:event_btEditActionPerformed

    private void btDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelActionPerformed
        if(this.txtMaDM.getText().length()==0)

        JOptionPane.showMessageDialog(null, "Bạn cần chọn Món để xoá", "Thông Báo",1);
        else
        {
            if(JOptionPane.showConfirmDialog(null, "Bạn đã xoá Món "+madm+"  ","Thông Báo",2)==0);
            DanhMuc.DeleteDM(madm);
            showCT();
            ProcessCtr(false);

        }
    }//GEN-LAST:event_btDelActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        showCT();
        ProcessCtr(false);
        this.txtMaDM.setText(null);
        this.txtTenDM.setText(null);
        this.txtText.setText(null);       
    }//GEN-LAST:event_HomeActionPerformed

    private void btRewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRewActionPerformed
       dispose();
    }//GEN-LAST:event_btRewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhMucTD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhMucTD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhMucTD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhMucTD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DanhMucTD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JButton New;
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDel;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btRew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTong;
    private javax.swing.JTable tbDanhmuc;
    private javax.swing.JTextField txtMaDM;
    private javax.swing.JTextField txtTenDM;
    private javax.swing.JTextField txtText;
    // End of variables declaration//GEN-END:variables
}
